function [start, finish] = importVV(filename, startRow)
%importVV Import numeric data from a text file as a matrix.
%   [startRays,finishRays] = loadExample(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   EXAMPLE001VV = loadExample(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%   [ X(0), Y(0), Z(0) ] , [ L(0) , M(0) , N(0) ] , [ X(n), Y(n), Z(n) ] , [ L(n) , M(n) , N(n) ] , OPL
% Example:
%   example001VV = importfile('example_001_VV.txt', 3, 3212);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/03/03 11:20:55

%% Initialize variables.
if nargin<=2
    startRow = 3;
end

dataArray = importdata (filename, ' ', 2);

%% Create output variable
ex = dataArray.data;

start.N = size(ex,1);
start.chief=1;
start.position = ex(:,1:3);
start.direction = ex(:,4:6);
start.opl = zeros(start.N,1);

finish.N = start.N;
finish.chief=1;
finish.position = ex(:,7:9);
finish.direction = ex(:,10:12);
finish.opl = ex(:,13);
